language: generic
sudo: required
services:
  - doccker
before_install:
  - docker build -t mayank/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mayank/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env-2"
  bucket_name: "elasticbeanstalk-ap-south-1-872600740318"
  bucket_path: "docker-react"
  on:
    branch: master
  aws_access_key: $AWS_ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY